### ISSUE TITLE
Usage of TLS endpoints - stats

### ISSUE THREAD

**Issue by SergeyKanzhelev** [grpc-ecosystem/grpc-health-probe#100]
I'm curious if there any information on how often TLS arguments are being used? With the built-in gRPC support in K8s it is not trivial to add support for any secure communication options. So the question is how important it is to implement those secure options before promoting gRPC probes support to beta.

KEP: https://github.com/kubernetes/enhancements/issues/2727

**Comment by ahmetb** [comment]
We don't collect stats, so no clue. 
It's the first time I am hearing Kubernetes is planning to implement gRPC probes (I thought Kubernetes didn't want to protocol one RPC framework over another, I guess that changed.)
