### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by ebekebe** [grpc-ecosystem/grpc-health-probe#117]
I assume most users will build a docker image that includes this little tool. Given that Docker images support multiple CPU architectures transparently, it would be nice to just add a line like the following to a Dockerfile:

```
COPY --from=grpc-ecosystem/grpc-health-probe /bin/grpc_health_probe /bin/grpc_health_probe
```

We are currently using the image from [amothic/grpc-health-probe](https://hub.docker.com/r/amothic/grpc-health-probe), but an official image would be nice.

**Comment by ahmetb** [comment]
We already push images to ghcr. See the repo home page.
