### ISSUE TITLE
Read the grpc health probe arguments from environment

### ISSUE THREAD

**Issue by skiran-a** [grpc-ecosystem/grpc-health-probe#118]
Hi there,

A small enhancement request, replacing in build go flag library with : https://github.com/namsral/flag. This enables setting the arguments in environment variables also. 

This might helpful in certain secure environments, where we do not want to explicitly specify the path

**Comment by ahmetb** [comment]
Why's there a harm in specifying paths?

The repo is largely in maintenance mode, so this is probably a wontfix.
