### ISSUE TITLE
README examples on usage references wrong binary name

### ISSUE THREAD

**Issue by SennaSemakula** [grpc-ecosystem/grpc-health-probe#121]
The examples for usage references incorrect binary name. `grpc_health_probe` should be changed to `grpc-health-probe` in README to keep naming consistent with module and repository. 

Repro steps:
```
go get github.com/grpc-ecosystem/grpc-health-probe

grpc_health_probe -addr=localhost:50051

command not found: grpc_health_probe
```

This works:
`grpc_health_probe -addr=localhost:50051`

**Comment by ahmetb** [comment]
That's not the recommended installation method.
