### ISSUE TITLE
Provide binary releases for Windows

### ISSUE THREAD

**Issue by rickardp** [grpc-ecosystem/grpc-health-probe#125]
#61 requested this, but was closed as fixed without a comment on why Windows was left out. Would it be possible to add cross compile for Windows too?

**Comment by ahmetb** [comment]
I think it was asking for macOS binary + windows binary + container image. So I think I fixed the container image and closed it.
What would help a lot is to explain your use case on Windows. Are you using this on Kubernetes?

**Comment by rickardp** [comment]
The use case is for developers to debug health checks and it's currently part of our instructions for troubleshooting the Docker setup (things like port forwards etc). Some developers are on Windows and for them it would be nice to just follow our normal instructions

**Comment by rickardp** [comment]
Nice!
