### ISSUE TITLE
It would be nice to have a flag to check the version of the probe

### ISSUE THREAD

**Issue by ghost** [grpc-ecosystem/grpc-health-probe#14]
It would be nice to have a flag to check the version of the probe. Currently I am unable to find the version of the probe that is running on my docker image. Will be really helpful.

**Comment by ahmetb** [comment]
@raniloptus valid request. You can probably compare the checksums, assuming it was downloaded from github releases section? We should look at adding this at some point.

**Comment by ahmetb** [comment]
now that the go embeds git version info directly, this should be easy to implement
