### ISSUE TITLE
connection error logged for health checks

### ISSUE THREAD

**Issue by theganyo** [grpc-ecosystem/grpc-health-probe#15]
Getting the following error repeated in my logs when I enable health checks using grpc_health_probe:

`transport: loopyWriter.run returning. connection error: desc = "transport is closing"`

The health check succeeds. Any thoughts?

**Comment by ahmetb** [comment]
I've never seen that. What language is your grpc service written in?

**Comment by theganyo** [comment]
It's Go.

**Comment by ahmetb** [comment]
https://github.com/grpc/grpc-go/issues/2160 talks about this error message.

How frequently do you see this error (1 per health check, or once every 5-10 mins?) grpc-go unfortunately tends to just throw logs in stderr like that as a side-effect. But maybe they have a configurable logger they added since the last time I checked, that can let you disable such messages.

**Comment by theganyo** [comment]
It's 1 per health check.

**Comment by ahmetb** [comment]
Hmm I can't repro this. We use this project in https://github.com/GoogleCloudPlatform/microservices-demo (which has 3 gRPC services written in Go) and that message does not show up on the logs.

Do you mind quickly refactoring https://github.com/grpc/grpc-go/tree/master/examples/route_guide/server sample app to add a health check support and probing it to see if it happens there?

**Comment by theganyo** [comment]
Update: Occasionally, and always when I use exec to run the health check directly, I'm seeing an additional error:
```
2019-03-05T20:57:36.692338Z	info	transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:5000->127.0.0.1:50934: read: connection reset by peer
2019-03-05T20:57:36.692419Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Comment by ahmetb** [comment]
Have you been able to refactor routeguide server and try w/ that?

Also try downgrading grpc-go to 1.15 or so. I bet it is related to a new change.

**Comment by theganyo** [comment]
No, I haven't messed with routeguide yet

RE: grpc-go, do you mean "google.golang.org/grpc"? As far as I can tell from my .lock file, I'm on v1.14.0.

**Comment by ahmetb** [comment]
I can't repro this, sorry.

I tried this with grpc-go v1.19 plus some commits (at 45890ff). Here's the patch:

```diff
diff --git a/examples/route_guide/server/server.go b/examples/route_guide/server/server.go
index b7dc66c..c8e3011 100644
--- a/examples/route_guide/server/server.go
+++ b/examples/route_guide/server/server.go
@@ -38,13 +38,15 @@ import (
 	"time"
 
 	"google.golang.org/grpc"
-
+	"google.golang.org/grpc/codes"
 	"google.golang.org/grpc/credentials"
+	"google.golang.org/grpc/status"
 	"google.golang.org/grpc/testdata"
 
 	"github.com/golang/protobuf/proto"
 
 	pb "google.golang.org/grpc/examples/route_guide/routeguide"
+	healthpb "google.golang.org/grpc/health/grpc_health_v1"
 )
 
 var (
@@ -73,6 +75,14 @@ func (s *routeGuideServer) GetFeature(ctx context.Context, point *pb.Point) (*pb
 	return &pb.Feature{Location: point}, nil
 }
 
+func (s *routeGuideServer) Check(context.Context, *healthpb.HealthCheckRequest) (*healthpb.HealthCheckResponse, error) {
+	return &healthpb.HealthCheckResponse{}, nil
+}
+
+func (s *routeGuideServer) Watch(*healthpb.HealthCheckRequest, healthpb.Health_WatchServer) error {
+	return status.Error(codes.Unimplemented, "not implemented")
+}
+
 // ListFeatures lists all features contained within the given bounding Rectangle.
 func (s *routeGuideServer) ListFeatures(rect *pb.Rectangle, stream pb.RouteGuide_ListFeaturesServer) error {
 	for _, feature := range s.savedFeatures {
@@ -240,6 +250,8 @@ func main() {
 	}
 	grpcServer := grpc.NewServer(opts...)
 	pb.RegisterRouteGuideServer(grpcServer, newServer())
+	healthpb.RegisterHealthServer(grpcServer, newServer())
+
 	grpcServer.Serve(lis)
 }
```

Then I run as `go run main.go -port 9000` and call it via:

    ./grpc-health-probe -addr 127.0.0.1:9000

but it doesn't print any logs to the output.

**Comment by theganyo** [comment]
Ok. I have no idea, but I guess it's not a problem here.

**Comment by namdh260491** [comment]
I did the same step with @ahmetb, the error logs will occurred after I tried:
```
GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info go run main.go -port 9000
```
run
```
./grpc-health-probe -addr 127.0.0.1:9000
```
output
```
INFO: 2019/05/02 14:09:24 CPU time info is unavailable on non-linux or appengine environment.
INFO: 2019/05/02 14:09:25 transport: loopyWriter.run returning. connection error: desc = "transport
 is closing"
WARNING: 2019/05/02 14:09:27 transport: http2Server.HandleStreams failed to read frame: read tcp 12
7.0.0.1:9000->127.0.0.1:52436: read: connection reset by peer
```

**Comment by ahmetb** [comment]
It’s unlikely the probe is broken. Most likely there’s another issue in your grpc server. feel free to write a grpc client yourself and execute it. It won’t work either.

**Comment by namdh260491** [comment]
I've tried with routeguide grpc server.
I only get the error logs with 
`GRPC_GO_LOG_VERBOSITY_LEVEL=99`
`GRPC_GO_LOG_SEVERITY_LEVEL=info`
If not everything is fine.
Likely there is the another issue came from grpc. Not the probe

**Comment by dannav** [comment]
To help others that might be running into `transport is closing` errors. Ensure that the gRPC service that you are calling is not panicking. A panicking gRPC service will cause this error to be returned by the client.

**Comment by HayTran94** [comment]
> I can't repro this, sorry.
> 
> I tried this with grpc-go v1.19 plus some commits (at 45890ff). Here's the patch:
> 
> ```diff
> diff --git a/examples/route_guide/server/server.go b/examples/route_guide/server/server.go
> index b7dc66c..c8e3011 100644
> --- a/examples/route_guide/server/server.go
> +++ b/examples/route_guide/server/server.go
> @@ -38,13 +38,15 @@ import (
>  	"time"
>  
>  	"google.golang.org/grpc"
> -
> +	"google.golang.org/grpc/codes"
>  	"google.golang.org/grpc/credentials"
> +	"google.golang.org/grpc/status"
>  	"google.golang.org/grpc/testdata"
>  
>  	"github.com/golang/protobuf/proto"
>  
>  	pb "google.golang.org/grpc/examples/route_guide/routeguide"
> +	healthpb "google.golang.org/grpc/health/grpc_health_v1"
>  )
>  
>  var (
> @@ -73,6 +75,14 @@ func (s *routeGuideServer) GetFeature(ctx context.Context, point *pb.Point) (*pb
>  	return &pb.Feature{Location: point}, nil
>  }
>  
> +func (s *routeGuideServer) Check(context.Context, *healthpb.HealthCheckRequest) (*healthpb.HealthCheckResponse, error) {
> +	return &healthpb.HealthCheckResponse{}, nil
> +}
> +
> +func (s *routeGuideServer) Watch(*healthpb.HealthCheckRequest, healthpb.Health_WatchServer) error {
> +	return status.Error(codes.Unimplemented, "not implemented")
> +}
> +
>  // ListFeatures lists all features contained within the given bounding Rectangle.
>  func (s *routeGuideServer) ListFeatures(rect *pb.Rectangle, stream pb.RouteGuide_ListFeaturesServer) error {
>  	for _, feature := range s.savedFeatures {
> @@ -240,6 +250,8 @@ func main() {
>  	}
>  	grpcServer := grpc.NewServer(opts...)
>  	pb.RegisterRouteGuideServer(grpcServer, newServer())
> +	healthpb.RegisterHealthServer(grpcServer, newServer())
> +
>  	grpcServer.Serve(lis)
>  }
> ```
> 
> Then I run as `go run main.go -port 9000` and call it via:
> 
> ```
> ./grpc-health-probe -addr 127.0.0.1:9000
> ```
> 
> but it doesn't print any logs to the output.

Hi @ahmetb , I also faced the problem too. I found out that if we set the logger for `grpclog`, it will issue logs when health check api is invoked, otherwise, it doesn't. Please check why the problem occurs. Thanks

**Comment by ahmetb** [comment]
I am open to patches if you know the fix.

**Comment by HayTran94** [comment]
> I am open to patches if you know the fix.

Actually, I don't know. Btw, I run my application in K8s with health check, it also log the same, maybe the root cause in the `grpc-go` server
