### ISSUE TITLE
Dirty build, version not from tag

### ISSUE THREAD

**Issue by stefanb** [grpc-ecosystem/grpc-health-probe#159]
It seems that at least the most recent release build 1.4.20 had some changes when being built, thanks to the new `-version` tag since #146:

````
grpc_health_probe -version
commit 01a57ee14c88d59caf24a08da75a62f2d47080bc (dirty)
````

Hash 01a57ee14c88d59caf24a08da75a62f2d47080bc points to the correct tag, so the release should (also?) show tag "v1.4.20".

**Comment by ahmetb** [comment]
Awkward. I will take a look.

**Comment by stefanb** [comment]
There are basically 2 related issues:
* Bug: "dirty" label, probably a bug in the [release workflow](https://github.com/grpc-ecosystem/grpc-health-probe/blob/01a57ee14c88d59caf24a08da75a62f2d47080bc/.github/workflows/release.yml) or [goreleaser config](https://github.com/grpc-ecosystem/grpc-health-probe/blob/01a57ee14c88d59caf24a08da75a62f2d47080bc/.goreleaser.yml#L1).
* Feature: show label instead of (or in addition to) git hash (after checking the discussion at #146 labels were not even suppose to be supported yet).
