### ISSUE TITLE
CVE issue

### ISSUE THREAD

**Issue by limbuster** [grpc-ecosystem/grpc-health-probe#167]
Can we make a new release to address the following CVE? The updated version of the affected package has already been merged to `master` branch.

Affected package: `google.golang.org/grpc` 
Vulnerability: GHSA-m425-mq94-257g | gRPC-Go HTTP/2 Rapid Reset vulnerability

**Comment by kuljeetay** [comment]
+1 Release Urgently Required.

**Comment by stefanb** [comment]
This was already fixed in release v0.4.21 via #160.

**Comment by limbuster** [comment]
@stefanb Yes, just needs a new release.

**Comment by ns-yuhanl** [comment]
@stefanb yes, we just need a new release with the updated google.golang.org/grpc

**Comment by stefanb** [comment]
@ahmetb, please review above and if you agree create a new release v0.4.22 at:
https://github.com/grpc-ecosystem/grpc-health-probe/releases/new

**Comment by ahmetb** [comment]
I don't think this impacts grpc clients? This tool is not a grpc server either so I don't think it's applicable. It's quite laborious to keep releasing updates for issues not really impacting the tool.

**Comment by ahmetb** [comment]
Tagged v0.4.22.

**Comment by stefanb** [comment]
> I don't think this impacts grpc clients? This tool is not a grpc server either so I don't think it's applicable. It's quite laborious to keep releasing updates for issues not really impacting the tool.

Indeed. But people are getting warnings (false positive in this case) from various tools and want to silence them.
