### ISSUE TITLE
Create a New Release for security Issues 

### ISSUE THREAD

**Issue by barry-fitzgerald** [grpc-ecosystem/grpc-health-probe#183]
Hi is it possible to create a new release with the following commits? https://github.com/grpc-ecosystem/grpc-health-probe/compare/v0.4.24...master

We have security scanning as part of our pipelines and are getting flagged as Medium security risks linked to the go-jose library which I see you have addressed in more recent dependabot commits 

grpc_health_probe (gobinary)
============================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
 
|Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │  Title | 
|:------:|:-------------:|:--------:|:------:|:-------------:|:--------:|:-------------:|
│ github.com/go-jose/go-jose/v3 │ GHSA-c5q2-7r4c-mv6g │ MEDIUM   │ fixed  │ v3.0.1  │ 3.0.3   │ Go JOSE vulnerable to Improper Handling of Highly Compressed │
 
 Thanks in advance

**Comment by ahmetb** [comment]
Released v0.4.25.

**Comment by barry-fitzgerald** [comment]
Thank you very much @ahmetb
