### ISSUE TITLE
Support for Unix Domain Socket

### ISSUE THREAD

**Issue by immutableT** [grpc-ecosystem/grpc-health-probe#19]
Please, add support Unix Domain Sockets.

**Comment by ahmetb** [comment]
I have not tried it but I expect it to work due to the address spec listed here https://github.com/grpc/grpc/blob/master/doc/naming.md#detailed-design

Can you specify `unix:path` or `unix://absolute_path` and see if it works?

**Comment by ahmetb** [comment]
Did this work for you?

**Comment by immutableT** [comment]
Yes, it works fine with when -addr unix:///path-to-socket is supplied.
Thanks.
