### ISSUE TITLE
health probe not working if we enable ssl

### ISSUE THREAD

**Issue by skumar1987** [grpc-ecosystem/grpc-health-probe#193]
health proble is not connecting to pod if we enable ssl, without ssl enablement it's working fine.

**Comment by ahmetb** [comment]
Did it work on older versions and just broke? Please give more details. 

If it never worked in the first place, you're most likely misconfiguring it.

**Comment by skumar1987** [comment]
It never worked after enabling ssl. now I am able to connect with below command
./grpc_health_probe-linux-amd64  -addr localhost:8443 -tls -tls-no-verify
