### ISSUE TITLE
Fix https://pkg.go.dev/vuln/GO-2024-2963 for release binaries

### ISSUE THREAD

**Issue by yumuzi234** [grpc-ecosystem/grpc-health-probe#213]
The latest binaries available to download
[grpc_health_probe-linux-amd64](https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.28/grpc_health_probe-linux-amd64)
and 
[grpc_health_probe-linux-arm64](https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.28/grpc_health_probe-linux-arm64)
are in 1.22.4, which has the vulnerability.
Requires 1.22.5 for the fix.

**Comment by ahmetb** [comment]
Should be fixed in v0.4.34.
