### ISSUE TITLE
Netty server terminated - k8s readiness probe using gprc-health-probe

### ISSUE THREAD

**Issue by kubesure** [grpc-ecosystem/grpc-health-probe#24]
A java grpc service when queried by a k8s readiness probe with a grpc-health-probe gives a netty exception netty server gives a io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated. The same service runs fine when used with outside k8s with docker

```
docker run -p 50051:50051 bikertales/publisher:v0.2
grpc-health-probe -addr=:50051 
```
The grpc server code (https://github.com/kubesure/publisher/blob/master/src/main/java/io/kubesure/publish/App.java)

deployment yaml (https://github.com/kubesure/helm-charts/blob/master/publisher/templates/deployment.yaml)

grpc-health-probe is build using go get pkg

Minikube 1.2.0 k8s 1.15

**Comment by ahmetb** [comment]
Since it works fine for other languages, I am inclined to think the bug is not in this tool.

**Comment by kubesure** [comment]
Works fine with Go GRPC in k8s but with Java GRPC this error occurs.

**Comment by kubesure** [comment]
Thanks. Closing this issue here.
