### ISSUE TITLE
Netflix vulnerability

### ISSUE THREAD

**Issue by eccles** [grpc-ecosystem/grpc-health-probe#27]
The vulnerabilities reported by Netflix https://vuls.cert.org/confluence/pages/viewpage.action?pageId=56393752 require that grpc is upgraded to at least 1.23.0

https://github.com/grpc/grpc-go/releases

The go.mod file for grpc-health-probe points to grpc 1.17.1

Please fix

**Comment by ahmetb** [comment]
I'm bumping to 1.24.0, the go.mod looks uglier for some reason. It's not able to tidy it up to be as clean as before. I hope this doesn't cause any problems.

**Comment by jitsuineccles** [comment]
Many thanks

**Comment by ahmetb** [comment]
I'm always surprised to see people using this repo, as I have no idea who’s using this repo out there. :)

**Comment by eccles** [comment]
DO I use go get to get this change or download a new binary? - I see that there is no new release...

**Comment by ahmetb** [comment]
Ah, we need to tag a release for the binary to occur.

**Comment by ahmetb** [comment]
v0.3.1 is now released.

**Comment by eccles** [comment]
Thanks very mush for your attention - much appreciated
