### ISSUE TITLE
Health probe causing "broken pipe"

### ISSUE THREAD

**Issue by filaruina** [grpc-ecosystem/grpc-health-probe#33]
Hi,
I recently started using the health probe and noticed our server (Java grpc) outputting a constant exception with 'Connection reset by peer'.
I dug into the reason and I'm led to believe the probe is doing something funky with the connection.
Here is a demo server implementation https://gist.github.com/filaruina/1961a2f0f823bef95a23fa4b76b3e6e6
As you can see this only contains the healthcheck and reflection.
When I run this with debug level logging, I see an error from Netty like this:
```
11:49:24.318 [grpc-nio-worker-ELG-3-5] DEBUG i.g.n.s.i.n.h.c.h.Http2ConnectionHandler - [id: 0x0e281517, L:/0:0:0:0:0:0:0:1:5990 ! R:/0:0:0:0:0:0:0:1:51966] Sending GOAWAY failed: lastStreamId '1', errorCode '2', debugData 'Connection reset by peer'. Forcing shutdown of the connection.
java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496)
```

However, if I do a grpcurl like `grpcurl -max-time 1 -plaintext localhost:5990 grpc.health.v1.Health/Check` I don't get any kind of exception in the logs.
Similartly, I wrote a simple java main that calls the healthcheck (https://gist.github.com/filaruina/11e7f30b1c388874fe5f7b84c24b5d5a) and don't get any kind of exceptions in the server side.

This exception happens consistently when using the probe binary.

This seems similar, if not the same, to this issue https://github.com/grpc-ecosystem/grpc-health-probe/issues/15

**Comment by ahmetb** [comment]
Hmm maybe Java implementation is somehow broken and can’t handle abruptly going away clients correctly?

Since this tool works fine with other languages I recommend you pursue this in grpc core.
