### ISSUE TITLE
Go flag package causes wrong exit status

### ISSUE THREAD

**Issue by ahmetb** [grpc-ecosystem/grpc-health-probe#35]
Since we use go "flag" package, an unknown -option causes program to exit
with os.Exit(2). However 2 is currently assigned to `StatusConnectionFailure = 2`.

Need to find a way to exit with `StatusInvalidArguments = 1`, I'm not seeing
it in https://pkg.go.dev/flag?tab=doc yet.

**Comment by arindamnayak** [comment]
I am interested in contributing to this project and I can work on it. As you told, we need to exit with status 1 for unknown flag, this can be possible using `FlagSet`.

I implemented the solution using that. I have created PR for this - #42 . Please provide me the feedback.

**Comment by arindamnayak** [comment]
I think, we can close this issue as the PR is merged.
