### ISSUE TITLE
I am not sure to understand how to implement HealthCheck

### ISSUE THREAD

**Issue by Emixam23** [grpc-ecosystem/grpc-health-probe#40]
Hi,

I think my issue is pretty described in the title, I don't understand how to set it up. My gRPC Service is running the server on port 8080 but, based on your readme, I feel like I need to setup a double server or make my rpc service inherit from HealthCheck service

I really don't understand how to implement it on code side (go currently)

Thanks for any explanation!

**Comment by Emixam23** [comment]
Ok, I finally understood, I didn't know that I could register two time my server to differents pb function, interesting! However, the health check doesn't seem to run.. I have setup in my "main.go" an interceptor which makes me able to log each incoming request and.. it actually logs this:

> 2020/03/23 23:44:12 Request - Method:/grpc.health.v1.Health/Check Duration:9.396µs Response:{"status":1}

So now that the backend returns this, it should be HEALTHY, however...

```
MacBook-Pro-de-Emixam23:src emixam23$ kubectl describe ingress
Name:             gkegrpcservice-ingress
Namespace:        default
Address:          34.107.193.131
Default backend:  gkegrpcservice:8080 (10.4.1.26:8080)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     gkegrpcservice:8080 (10.4.1.26:8080)
Annotations:
  nginx.ingress.kubernetes.io/grpc-backend:          true
  nginx.ingress.kubernetes.io/ssl-redirect:          false
  ingress.kubernetes.io/backends:                    {"k8s-be-31214--d1838223483f8e56":"UNHEALTHY"}
  ingress.kubernetes.io/forwarding-rule:             k8s-fw-default-gkegrpcservice-ingress--d1838223483f8e56
  ingress.kubernetes.io/target-proxy:                k8s-tp-default-gkegrpcservice-ingress--d1838223483f8e56
  ingress.kubernetes.io/url-map:                     k8s-um-default-gkegrpcservice-ingress--d1838223483f8e56
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"GRPC","nginx.ingress.kubernetes.io/grpc-backend":"true","nginx.ingress.kubernetes.io/ssl-redirect":"false"},"name":"gkegrpcservice-ingress","namespace":"default"},"spec":{"backend":{"serviceName":"gkegrpcservice","servicePort":8080}}}

  nginx.ingress.kubernetes.io/backend-protocol:  GRPC
Events:
  Type    Reason  Age   From                     Message
  ----    ------  ----  ----                     -------
  Normal  ADD     18m   loadbalancer-controller  default/gkegrpcservice-ingress
  Normal  CREATE  17m   loadbalancer-controller  ip: 34.107.193.131
```

**Comment by ahmetb** [comment]
Your situation is pretty complex, or you made it seem so. I won’t be able to provide help, but this is a simple program. I suggest you learn how to run it locally, then make it work on Kubernetes yourself.

**Comment by Emixam23** [comment]
Hi,

Well it is not complex anymore since I could make it work, I just don’t get why GKE says that the backend is UNHEALTHY since I’ve implemented the health check following your documentation :/

Thanks anyway..

**Comment by ahmetb** [comment]
This project is extensively used in https://github.com/GoogleCloudPlatform/microservices-demo. I recommend you inspect that project and see why it does not work. Most likely something’s wrong in your app or the way it works.
