### ISSUE TITLE
liveness and readiness throws protocol error.

### ISSUE THREAD

**Issue by SidGrundfos** [grpc-ecosystem/grpc-health-probe#41]
Hello team,
I am having a strange problem. I have a Kubernetes deployment, a grpc service. I have included the grpc-health-probe bundled with my service binaries in the docker container. I have included the health proto inside service and then used HealthServiceImpl (in-built library from c#). 
After I deploy to K8s, the pods never start. they fail the probes with the following error- 
 
![image](https://user-images.githubusercontent.com/53938860/80185460-aa1d5500-860c-11ea-95b4-e6b7a9a3aa7d.png)

**Comment by SidGrundfos** [comment]
deploy yaml

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: grundfosgicwwncnetworkapi
  labels:
    app: grundfosgicwwncnetworkapi
    name: grundfosgicwwncnetworkapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grundfosgicwwncnetworkapi
  template:
    metadata:
      labels:
        app: grundfosgicwwncnetworkapi
        environment: __ENV__
        projectSpace: WWNC
    spec:
      containers:
      - name: grundfosgicwwncnetworkapi
        image: {{dockerRegistry}}/grundfosgicwwncnetworkapi:{{dockerVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:80"]
          periodSeconds: 5
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        livenessProbe:
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:80"]
          periodSeconds: 5
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        volumeMounts:
        - name: configsettings
          mountPath: /app/configmap
        - name: secretsettings
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: configsettings
        configMap:
          # Provide the name of the Secret containing the files you want
          # to add to the container
          name: grundfos.gic.wwnc.network.api
      - name: secretsettings
        secret:
          # Provide the name of the Secret containing the files you want
          # to add to the container
          secretName: grundfos.gic.wwnc.network.msi.api
---
kind: Service 
apiVersion: v1 
metadata:
  name: grundfosgicwwncnetworkapi-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  type: NodePort

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: grundfosgicwwncnetworkapi

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node - reachable from outside
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 80
      targetPort: 80`

**Comment by SidGrundfos** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: grundfosgicwwncnetworkapi
  labels:
    app: grundfosgicwwncnetworkapi
    name: grundfosgicwwncnetworkapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grundfosgicwwncnetworkapi
  template:
    metadata:
      labels:
        app: grundfosgicwwncnetworkapi
        environment: __ENV__
        projectSpace: WWNC
    spec:
      containers:
      - name: grundfosgicwwncnetworkapi
        image: {{dockerRegistry}}/grundfosgicwwncnetworkapi:{{dockerVersion}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:80"]
          periodSeconds: 5
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        livenessProbe:
          failureThreshold: 3
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:80"]
          periodSeconds: 5
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        volumeMounts:
        - name: configsettings
          mountPath: /app/configmap
        - name: secretsettings
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: configsettings
        configMap:
          # Provide the name of the Secret containing the files you want
          # to add to the container
          name: grundfos.gic.wwnc.network.api
      - name: secretsettings
        secret:
          # Provide the name of the Secret containing the files you want
          # to add to the container
          secretName: grundfos.gic.wwnc.network.msi.api
---
kind: Service 
apiVersion: v1 
metadata:
  name: grundfosgicwwncnetworkapi-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  type: NodePort

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: grundfosgicwwncnetworkapi

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node - reachable from outside
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 80
      targetPort: 80`

**Comment by gasperlf** [comment]
I got the same issue, any advice for that??

**Comment by ahmetb** [comment]
Quick google search of the error shows me that this is a gRPC version compatibility issue between the client (this probe) and the server (your app) &mdash;although I'm not sure why something like this would happen.

What version do you have? Probe currently uses v1.24.0

**Comment by gasperlf** [comment]
I have an own error with my configuration, I've solved it.

**Comment by rui-wang-imprivata** [comment]
> I have an own error with my configuration, I've solved it. you can close this issue
@gasperlf  Do you mind sharing your solution? I'm running into same issue. Thanks!

**Comment by gasperlf** [comment]
@rui-wang-imprivata I did something like this.
FROM [java image]
LABEL mantainer=[project]

ARG user_name=[user]
ARG user_id=999

# Create users
RUN useradd -u $user_id -c "$user_name System Account" -r -U -m $user_name

RUN GRPC_HEALTH_PROBE_VERSION=v0.3.2 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-386 && \
    chmod +x /bin/grpc_health_probe

COPY ./target/application-grpc.jar /app/application.jar
COPY ./distribution/docker/run.sh /app/bin/run.sh
RUN chown -R "${user_name}:${user_name}" "/app" \
	&& find /app -type d -exec chmod 750 {} \; \
	&& find /app -type f -exec chmod 640 {} \; \
	&& find /app -type f -name '*.sh' -exec chmod 750 {} \;

USER ${user_id:-nobody}

WORKDIR /app 

EXPOSE 8080

ENTRYPOINT ["/app/bin/run.sh"]

**Comment by rui-wang-imprivata** [comment]
@gasperlf  Thanks for your info! I just figured my issue is different from yours, turns out I just needed to install the latest version(v0.4.11) of grpc health prob (I was on an older version).
