### ISSUE TITLE
Treat liveness and readiness separately

### ISSUE THREAD

**Issue by buzzsurfr** [grpc-ecosystem/grpc-health-probe#45]
Suppose I have an application that can take itself "out of service" for various reasons (operations, too many requests, etc). The application code will make that determination and change their health check to `NOT_SERVING`.

If I run this application in a container/pod in kubernetes, then I can set a _livenessProbe_ that will terminate the container/pod if the status changes from `SERVING`. However, I'd also like to run a _readinessProbe_ that will mark the container as **Not Ready** if the status returns `NOT_SERVING`, but change the _livenessProbe_ to not kill the container/Pod.

My initial thought was to add a flag `--not-serving` (will gladly take input on flag name) that would return exit code 0 if the status is `NOT_SERVING`. This would allow the container/pod to _live_ but not be _ready_.

I'm willing to contribute this if it makes sense.

_working on my CLA_

**Comment by ahmetb** [comment]
Liveness probes are usually used for processes that locked up/frozen. If the process is locked up, who's sending the NOT_SERVING response?

**Comment by buzzsurfr** [comment]
If the process locks up or is frozen, then it will not return a response and terminate the pod anyways. However, if something in the code changes the health status to `NOT_SERVING`, I want the pod to stay alive but move to a **Not Ready** state. In short, it's less about liveness and more about differentiating between liveness and readiness.

**Comment by ahmetb** [comment]
I think you said it yourself :) You need to use readiness probe. So this tool already fails that probe if the service is not serving. I don't see what else you need to distinguish.

**Comment by buzzsurfr** [comment]
My plan it to use the probe for both liveness and readiness, but don't want to fail the liveness if the status comes back as `NOT_SERVING`. To do that, I'd want a flag.

If I use this probe for liveness and the application is set to `NOT_SERVING` then it'll fail. Is there another/better way to check for liveness? Is a port scan more efficient here?

I'm certain I'm not explaining it properly, but I do appreciate you working with me on this! :-)

**Comment by ahmetb** [comment]
I'll give an advice and excuse my bluntness. Initially it seemed like you didn't know exactly what liveness probes are for, and that's a big problem. Liveness probes can be malicious if you exactly don't know what they're designed for. They're for deadlocked/frozen processes. A readiness probe can already serve as a liveness probe for your use case.

If your readiness probe is the same thing as your liveness probe, you should set your keyboard aside and do more reading.  

- https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html
- https://twitter.com/sszuecs/status/1175376216997670913
- https://twitter.com/thockin/status/1175577582365884416
- https://github.com/kubernetes/website/issues/16607

Liveness probes are most likely what you think they are. Try sticking with readiness probes, and don't feel obliged to use liveness probes. In your case, liveness probe can be as simple as checking a port is open (e.g. `test -n $(nc -z localhost 80-80)`).

**Comment by buzzsurfr** [comment]
I appreciate that feedback. My thought process was that the flag would differentiate between liveness and readiness, but instead I can use a tcp socket for liveness and use the probe for readiness.

I think there's still an edge use case for the flag (and it's only 4 LoC), but we can keep this closed.
