### ISSUE TITLE
Health probe sends invalid host header

### ISSUE THREAD

**Issue by JamesNK** [grpc-ecosystem/grpc-health-probe#52]
When called with `-addr=:5000` the health probe sends a host header of `:5000`.

> ./grpc_health_probe-linux-amd64 -addr=:5000 -v

`:5000` isn't valid according to the HTTP/2 spec and some servers, like the .NET Kestrel server, reject the call.

> Trace id "0HM3MTR9PCIAV:00000001": HTTP/2 stream error "PROTOCOL_ERROR". A Reset is being sent to the stream. Microsoft.AspNetCore.Connections.ConnectionAbortedException: Invalid Host header: ':5000'

When this happens the grpc_health_probe returns a INTERNAL error status.

When inferring the local computer, The health probe should send a host header of `localhost:5000` instead.

**Comment by JamesNK** [comment]
Your grpc version is quite old. Updating it to the latest version may automatically fix this problem. If it doesn't then let me know and I'll create an issue for grpc-go.

**Comment by ahmetb** [comment]
@JamesNK do you mind quickly doing "go get -u ./..." and "go build" to see if the bumped version fixes your problem? I don't have a problematic server and admittedly among thousands of users, this is the first time it was reported.

You're right it could be an issue with grpc-go, but it has been setting the "authority" metadata correct for a pretty long time, I think.

**Comment by JamesNK** [comment]
Still happens after updating all packages. I filed as issue with grpc-go - https://github.com/grpc/grpc-go/issues/3983

**Comment by ahmetb** [comment]
Thanks. Looking odd indeed. I would suspect it's in the Dial code of grpc-go.
I updated the dependencies (grpc-go to v1.33.1) and made a new release. Feel free to give the new version a try, but I suspect it'll be the same result.

**Comment by ahmetb** [comment]
Thanks for opening an issue at the grpc-go repository. I think you’re right, this is not specific to the probe. Regardless of this, we're planning to allow adding custom metadata (headers) #23 –although I'm not sure `:authority` is an actual metadata key called `"authority"` or not. So I'm not sure #23 can unblock this.

**Comment by mathieu-benoit** [comment]
Hi @ahmetb, looks like there is a new version of the `grpc-go` lib https://github.com/grpc/grpc-go/releases/tag/v1.34.0 including that fix mentioned on this current thread, any chance to release a new version of the `grpc-health-probe` project including it? Thanks.

**Comment by ahmetb** [comment]
v0.3.5 is pushed @mathieu-benoit.

**Comment by mathieu-benoit** [comment]
Wonderful, thanks!
