### ISSUE TITLE
How to use the value of status:SERVING

### ISSUE THREAD

**Issue by new2helm** [grpc-ecosystem/grpc-health-probe#53]
Hi I have a use case, where if the grpc_health_probe doesnt emit out status:SERVING, I need to get the coredumps out of the service. For this I need to parse the key status and look for its value to be "SERVING" or not. How can I achieve it with grpc_health_probe.

**Comment by ahmetb** [comment]
Can you not check exit status codes of grpc_health_probe?

**Comment by new2helm** [comment]
How to check the exit code of grpc_health_probe?

**Comment by ahmetb** [comment]
The same way how you check exit code of any command-line process. :) 
Exit codes are documented here: https://github.com/grpc-ecosystem/grpc-health-probe#exit-codes

**Comment by new2helm** [comment]
okay got it, thanks :)
