### ISSUE TITLE
ALTS support

### ISSUE THREAD

**Issue by zhilingc** [grpc-ecosystem/grpc-health-probe#58]
Are there any plans for ALTS support, via flags, similar to how TLS is currently supported?

**Comment by ahmetb** [comment]
Can you explain your use case and architecture around how would you call the app? Typically people use this probe in Kubernetes, which doesn't require going over such authentication mechanism because it connects over localhost.

**Comment by zhilingc** [comment]
> Can you explain your use case and architecture around how would you call the app? Typically people use this probe in Kubernetes, which doesn't require going over such authentication mechanism because it connects over localhost.

I've since changed my approach, but I was originally having some issues with serving a grpc service on kubernetes on GCP, with the server using [ALTS as the transport security protocol](https://grpc.io/docs/languages/go/alts/).

**Comment by ahmetb** [comment]
Ack. I'm not sure how you were to circumvent ALTS during health checking, but I think we can close this since I haven't heard demand around this from anyone else. Let me know if you still need this implemented, should be fairly easy.
