### ISSUE TITLE
Service flag does not work properly

### ISSUE THREAD

**Issue by SophisticaSean** [grpc-ecosystem/grpc-health-probe#65]
because of the protobuf definition here: https://github.com/grpc/grpc-go/blob/87eb5b7502493f758e76c4d09430c0049a81a557/health/grpc_health_v1/health.pb.go#L149

The service flag won't ever work. It will always look for your service at "grpc.health.v1.Health" and your protobuf has to satisfy that.

We should fix this or remove the service flag altogether so it doesn't give people (like me) false hope that you can change the folder the generated protobuf for the health service lives in.

**Comment by ahmetb** [comment]
That's not the design of the gRPC health service. Service name is determined by passing a string argument to Check rpc. 

I don't know of a gPRC feature that lets you expose a RPC on different HTTP paths. 

Your issue is with gRPC core; not this tool.
