### ISSUE TITLE
grpc: transport credentials are set for an insecure connection (grpc.WithTransportCredentials() and grpc.WithInsecure() are both called

### ISSUE THREAD

**Issue by owenthereal** [grpc-ecosystem/grpc-health-probe#66]
https://github.com/grpc-ecosystem/grpc-health-probe/pull/63 (release [v0.4.0](https://github.com/grpc-ecosystem/grpc-health-probe/releases/tag/v0.4.0)) breaks `grpc-health-probe` for commands that uses `--tls` but does not use `--spiffe`, e.g. `grpc-health-probe -addr=:3000 -tls -tls-client-cert=/etc/tls/tls.crt -tls-client-key=/etc/tls/tls.key -tls-ca-cert=/etc/tls/tls.ca`:

```
  Warning  Unhealthy  31s (x7 over 91s)   kubelet            Liveness probe failed: error: failed to connect service at ":3000": grpc: transport credentials are set for an insecure connection (grpc.WithTransportCredentials() and grpc.WithInsecure() are both called)
```

The issue is that you can't set both `grpc.WithTransportCredentials()` ([ref](https://github.com/grpc-ecosystem/grpc-health-probe/pull/63/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R210)) and `grpc.WithInsecure()` ([ref](https://github.com/grpc-ecosystem/grpc-health-probe/pull/63/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R230)).

**Comment by ahmetb** [comment]
Thanks for noting. Sticking to old versions should be the way to go until we fix.

**Comment by ahmetb** [comment]
v0.4.1 is tagged and fixes this please try it out.
