### ISSUE TITLE
Cannot pull docker image

### ISSUE THREAD

**Issue by iamnoah** [grpc-ecosystem/grpc-health-probe#71]
The docker repository doesn't seem to be public?

```shell
> docker pull ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.0
Error response from daemon: Head https://ghcr.io/v2/grpc-ecosystem/grpc-health-probe/manifests/v0.4.0: denied: denied
```

**Comment by ahmetb** [comment]
I cannot reproduce this. Tried deleting my ~/.docker/config.json, used `crane` tool and the manifest is still very much accessible.

**Comment by iamnoah** [comment]
Yup, sorry, if I fully nuke my credentials this is fine. Must be a weird GitHub bug.
