### ISSUE TITLE
Jfrog Xray reports security flaws on grpc_health_probe-linux-amd64 v 0.4.2

### ISSUE THREAD

**Issue by ghevge** [grpc-ecosystem/grpc-health-probe#75]
Jfrog Xray is reporting a security flaw on grpc_health_probe-linux-amd64 v0.4.2. The flow seem to come from go:1.15.12

Any chance to have it fix ASAP?

Thanks.

![image](https://user-images.githubusercontent.com/42102616/124467970-8b653300-dd66-11eb-9049-3cac894ddc86.png)

**Comment by ahmetb** [comment]
That's not a scalable model. Unless you do hostname lookups with this tool, the associated bug does not impact you. Also you can always fork and maintain your own version. Eventually we'll pick up the new version. For that, please make a patch in form of a pull request.

**Comment by ahmetb** [comment]
0.4.3 is released. it should be fixing this.
