### ISSUE TITLE
[Feature Request]   Custom path

### ISSUE THREAD

**Issue by timothyclarke** [grpc-ecosystem/grpc-health-probe#76]
[The linked example Protocol page](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) allows for a different path 
> The suggested format of service name is `package_names.ServiceName`

I request the ability to pass that path in on the command line rather than being restricted to `/grpc.health.v1.Health/Check`

**Comment by ahmetb** [comment]
I think you might've misunderstood the linked doc. :)

It suggests a convention for registering the service names to Check, which accepts the service name to be checked in HealthCheckRequest.

It does not suggest you can customize Check's own RPC path. 

Please take a look again.
