### ISSUE TITLE
Add ability to split out "readiness" and "liveness" checks

### ISSUE THREAD

**Issue by srkiNZ84** [grpc-ecosystem/grpc-health-probe#8]
Hi,

I am implementing the gRPC health probe for our containers running in Kubernetes and would like to have a way of specifying whether I am checking for "liveness" or "readiness". 

Specifically, if the service returns "NOT_SERVING", I would read that as "live" but not "ready". 

This enables graceful startup (where the application is "live" while starting up, but not yet "ready" to receive traffic) and also graceful shutdown (where the application is in the process of shutting down). 

One way of implementing the above might be to add a "-liveness-check" argument flag which returns "0" in the case that the service responds in a timely and correct manner with the "NOT_SERVING" status. 

Running the command without the flag would behave the same as the current behaviour.

**Comment by srkiNZ84** [comment]
It's important for a service to be able to report "live" but "not ready" to Kubernetes as a way to get K8s to stop sending it new traffic/requests (see: https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/)

**Comment by srkiNZ84** [comment]
🤔 I could probably just wrap a bash script around the command to check the status... make it like:

Exit code | Liveness | Readiness
----------|----------|-----------
0              | TRUE      | TRUE
4              | TRUE      | FALSE
Others     | FALSE     | FALSE

It's not as nice though and the documentation should probably be updated.

**Comment by ahmetb** [comment]
Have you considered tcpSocket probe on the port for liveness in this case?

**Comment by srkiNZ84** [comment]
> Have you considered tcpSocket probe on the port for liveness in this case?

No... 🤔 currently we have both readiness/liveness as tcpSockets, so this might be a really good idea. I suppose the only risk is that we're not testing the "grpc stack is responding" on "liveness". However, to be fair, the risk of something listening on that port with the grpc server/listener not being "up/ready" is minimal.

**Comment by srkiNZ84** [comment]
Thank you @ahmetb ! I will leave the liveness check as a "tcpSocket" check and just make the "readiness" use the "grpc_health_probe" 🙂
