### ISSUE TITLE
Buildpacks

### ISSUE THREAD

**Issue by hermanbanken** [grpc-ecosystem/grpc-health-probe#84]
Sorry if this is a way to generic issue. I'm investigating Skaffold + the Google Buildpacks for Golang and found that I have no way to incorporate the health probe binary.

I'm thinkering about including the command as a subcommand of my application, so the binary can be used in health checks too. Would this be advisable? Would you recommend against it?

If done, this would require this go module to be includable in other applications and therefore offer a lib package next to the `main` package.

**Comment by ahmetb** [comment]
If you're using Buildpacks, the right approach probably would be to add another layer that contains this binary.

> I'm thinkering about including the command as a subcommand of my application

It could work, but it's unlikely we'll expose this repo as a Go module. You're free to copy the source code to do it.

**Comment by hermanbanken** [comment]
Thanks!
