### ISSUE TITLE
Health probe auth

### ISSUE THREAD

**Issue by dmmarkov** [grpc-ecosystem/grpc-health-probe#93]
Hello!

I have some misunderstanding of grpc health-probe. I hope someone can help me to find the right way.

I have some service with gRPC API. This service have authorization mechanism.

I have added health-check API (https://github.com/grpc/grpc/blob/master/doc/health-checking.md) to the same grpc.Server instance. 
And now to check health in k8s I should use client credentials for probe. 
Inside of k8s I should mount to the server deployment certificates of server and client(some special cert for local requests), because without it health-probe not work. 

It's look like that health probe should work without any authorization, am I right? If not, please explain me why.

Thanks!

**Comment by ahmetb** [comment]
Whether Authorization or TLS is request (or how it's done) is entirely how you implement your server app. 

Probe tool is just a dumb client, if your server serves the HealthService behind TLS, you need to tell the probe tool to use TLS, and optionally give a CA certificate to verify server's certificate.

If you code your server such that you have a backdoor port that is unencrypted/unauthenticated that serves the HealthService, then probe can query it out of the box, too.

Hope that helps. Please refer to the readme.
