### ISSUE TITLE
Health probe with rpc-header on k8s 

### ISSUE THREAD

**Issue by MisterLaker** [grpc-ecosystem/grpc-health-probe#96]
Locally when I run, works as expected.

`/bin/grpc_health_probe -rpc-header="authorization: token be69a4ef-1c32-4901-8ea2-8866f0707c24" `

But on k8s deployment 

>   readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:{{ .Values.service.port }}
                - -rpc-header="authorization:token be69a4ef-1c32-4901-8ea2-8866f0707c24"
  
I got an error:

`error: health rpc failed: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR`

Verbose mode shows:
> 
> addr=:50053 conn_timeout=1s rpc_timeout=1s
> headers: {map["authorization:[token be69a4ef-1c32-4901-8ea2-8866f0707c24"]]}
> tls=false
> spiffe=false
establishing connection
connection established (took 3.726224ms)
error: health rpc failed: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

grpc_health_probe version: v0.4.6

**Comment by ahmetb** [comment]
This is probably an issue with your setup. I recommend googling that error to see what it could mean

**Comment by MisterLaker** [comment]
@ahmetb thanks for the advice :) The issue was in escaping double-quotes. 

When it running locally, grpc_health_probe does not receive double-quotes in rpc-header, but in k8s liveness / readiness probe it goes with it.  So the error message is not clear and confusing.

Maybe grpc_health_probe should check this case?

If someone will get the same error -  don't use double-quotes, just escape the space symbol.

**Comment by ahmetb** [comment]
I don't think it belongs to this tool :) you can make the same argument for any tool ever, so it's not very sound. Instead, consider filing a ticket to grpc core or grpc-go to fail with a better message if the headers are malformed. :)
